spring:
  datasource:
    # ??: jdbc:h2:~/querydsl
    # jdbc:h2:tcp://localhost/~/querydsl
    url: jdbc:h2:mem:querydsl++
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

    devtools:
      livereload:
        enabled: true
      restart:
        enabled: false

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace